### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by Redaktionen** [c4all/c4all#20]
We have stopped using c4all after discovering a major security problem. Hackers used c4all to access our site and change its content. /8 Sidor

**Comment by cvitan** [comment]
This should be resolved with the updates in 2.0.1 - note hiowever that there is a breaking change: The jsonfield library is replaced with the native Django.contrib.postgres.fields.JSONField - this unfortunately makes it necessary to rebuild the database from scratch.
